import json
import jsonpath

vegetable = {
    "vegetables": {
        "list": [
            {
                "id": 1278378,
                "prodName": "大白菜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "0.8",
                "highPrice": "1.0",
                "avgPrice": "0.9",
                "place": "冀鲁",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278377,
                "prodName": "娃娃菜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.2",
                "highPrice": "1.5",
                "avgPrice": "1.35",
                "place": "豫冀",
                "specInfo": "大",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278376,
                "prodName": "小白菜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "0.9",
                "highPrice": "1.0",
                "avgPrice": "0.95",
                "place": "冀",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278375,
                "prodName": "圆白菜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "0.8",
                "highPrice": "1.0",
                "avgPrice": "0.9",
                "place": "冀",
                "specInfo": "暄",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278374,
                "prodName": "圆白菜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "0.55",
                "highPrice": "0.65",
                "avgPrice": "0.6",
                "place": "冀",
                "specInfo": "露地",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278373,
                "prodName": "紫甘蓝",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "0.8",
                "highPrice": "1.0",
                "avgPrice": "0.9",
                "place": "滇闽",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278372,
                "prodName": "芹菜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.5",
                "highPrice": "1.8",
                "avgPrice": "1.65",
                "place": "冀京",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278371,
                "prodName": "西芹",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "2.3",
                "highPrice": "2.5",
                "avgPrice": "2.4",
                "place": "豫辽",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278370,
                "prodName": "菠菜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.2",
                "highPrice": "1.5",
                "avgPrice": "1.35",
                "place": "冀鲁",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278369,
                "prodName": "莴笋",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.0",
                "highPrice": "1.4",
                "avgPrice": "1.2",
                "place": "鲁津",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278368,
                "prodName": "团生菜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "0.8",
                "highPrice": "1.3",
                "avgPrice": "1.05",
                "place": "京冀",
                "specInfo": "白球\\净",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278367,
                "prodName": "散叶生菜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.5",
                "highPrice": "2.0",
                "avgPrice": "1.75",
                "place": "冀辽",
                "specInfo": "毛\\净",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278366,
                "prodName": "罗马生菜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "2.5",
                "highPrice": "3.0",
                "avgPrice": "2.75",
                "place": "冀滇",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278365,
                "prodName": "油菜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "0.8",
                "highPrice": "1.2",
                "avgPrice": "1.0",
                "place": "冀鲁",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278364,
                "prodName": "香菜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "3.0",
                "highPrice": "4.0",
                "avgPrice": "3.5",
                "place": "冀",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278363,
                "prodName": "茴香",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.0",
                "highPrice": "1.5",
                "avgPrice": "1.25",
                "place": "冀",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278362,
                "prodName": "韭菜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.0",
                "highPrice": "1.2",
                "avgPrice": "1.1",
                "place": "冀",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278361,
                "prodName": "苦菊",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.4",
                "highPrice": "2.0",
                "avgPrice": "1.7",
                "place": "冀辽",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278360,
                "prodName": "油麦菜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.3",
                "highPrice": "2.0",
                "avgPrice": "1.65",
                "place": "冀",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278359,
                "prodName": "散菜花",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.5",
                "highPrice": "2.8",
                "avgPrice": "2.15",
                "place": "苏陕豫",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278358,
                "prodName": "绿菜花",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "2.0",
                "highPrice": "2.5",
                "avgPrice": "2.25",
                "place": "鲁陕苏",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278357,
                "prodName": "绿豆芽",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "0.95",
                "highPrice": "1.0",
                "avgPrice": "0.98",
                "place": "",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278356,
                "prodName": "黄豆芽",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "0.85",
                "highPrice": "0.9",
                "avgPrice": "0.88",
                "place": "",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278355,
                "prodName": "番茄",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "2.8",
                "highPrice": "3.0",
                "avgPrice": "2.9",
                "place": "蒙冀",
                "specInfo": "黑框",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278354,
                "prodName": "番茄",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "3.0",
                "highPrice": "3.5",
                "avgPrice": "3.25",
                "place": "甘蒙",
                "specInfo": "纸箱",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278353,
                "prodName": "番茄",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "3.5",
                "highPrice": "3.8",
                "avgPrice": "3.65",
                "place": "蒙",
                "specInfo": "白框",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278352,
                "prodName": "黄瓜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.0",
                "highPrice": "1.6",
                "avgPrice": "1.3",
                "place": "鲁辽",
                "specInfo": "袋\\箱",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278351,
                "prodName": "黄瓜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.8",
                "highPrice": "2.4",
                "avgPrice": "2.1",
                "place": "冀",
                "specInfo": "鲜干花",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278350,
                "prodName": "小黄瓜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "3.0",
                "highPrice": "4.0",
                "avgPrice": "3.5",
                "place": "辽鲁",
                "specInfo": "旱\\荷兰",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278349,
                "prodName": "茄子",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.5",
                "highPrice": "2.5",
                "avgPrice": "2.0",
                "place": "蒙鲁冀",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278348,
                "prodName": "长茄",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.3",
                "highPrice": "2.2",
                "avgPrice": "1.75",
                "place": "冀辽",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278347,
                "prodName": "广茄",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "2.5",
                "highPrice": "3.0",
                "avgPrice": "2.75",
                "place": "云粤",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278346,
                "prodName": "线茄",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "2.0",
                "highPrice": "3.5",
                "avgPrice": "2.75",
                "place": "冀云",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278345,
                "prodName": "冬瓜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.5",
                "highPrice": "1.7",
                "avgPrice": "1.6",
                "place": "琼",
                "specInfo": "吊",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278344,
                "prodName": "冬瓜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "0.8",
                "highPrice": "1.0",
                "avgPrice": "0.9",
                "place": "桂",
                "specInfo": "地",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278343,
                "prodName": "毛冬瓜",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "1.6",
                "highPrice": "2.3",
                "avgPrice": "1.95",
                "place": "冀",
                "specInfo": "长条",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278342,
                "prodName": "架豆",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "5.5",
                "highPrice": "6.5",
                "avgPrice": "6.0",
                "place": "鲁",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278341,
                "prodName": "豆王",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "5.0",
                "highPrice": "6.0",
                "avgPrice": "5.5",
                "place": "云鲁",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278340,
                "prodName": "扁豆",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "4.0",
                "highPrice": "4.5",
                "avgPrice": "4.25",
                "place": "云鲁",
                "specInfo": "",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            },
            {
                "id": 1278339,
                "prodName": "豇豆",
                "prodCatid": 1186,
                "prodCat": "蔬菜",
                "prodPcatid": "",
                "prodPcat": "",
                "lowPrice": "4.5",
                "highPrice": "6.0",
                "avgPrice": "5.25",
                "place": "桂琼鲁",
                "specInfo": "白（粗）\\绿（细）",
                "unitInfo": "斤",
                "pubDate": "2022-05-10 00:00:00",
                "status": "",
                "userIdCreate": 138,
                "userIdModified": "",
                "userCreate": "admin",
                "userModified": "",
                "gmtCreate": "",
                "gmtModified": ""
            }
        ]
    }
}

name_list = jsonpath.jsonpath(vegetable, '$..prodName')
for name in name_list:
    print(name)
